language: java
notifications:
  email: false
jdk:
  - openjdk8
env:
  - ANT_ARGS="-logger org.apache.tools.ant.listener.AnsiColorLogger -Dnet.furfurylic.chionographis.squelch=true"
script:
  - ant clean
  - ant
  - ant -lib build -f test/test.xml
